[conditions]
reference = "/home/rory/data/refs/2019-nCoV.fa"

[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "localhost"
port = "5555"
barcode_kits = [ "SQK-RLB001",]

[conditions.classified]
name = "classified"
control = false
min_chunks = "0"
max_chunks = "2"
targets = []
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"

[conditions.unclassified]
name = "unclassified_reads"
control = false
min_chunks = "0"
max_chunks = "2"
targets = []
single_on = "unblock"
single_off = "unblock"
multi_on = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

[conditions.barcode02]
name = "barcode02"
control = false
min_chunks = "0"
max_chunks = "2"
targets = []
single_on = "unblock"
single_off = "unblock"
multi_on = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
